# Default
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/web
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 990909
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

---

# 운영 설정 
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://crud-maria:3306/web
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 990909
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: true
    prefix: classpath:/templates/